spring:
  application:
    name: 16-async-scheduling-batch-exercises
  threads:
    virtual:
      enabled: true
  batch:
    job:
      enabled: false                    # the tests start the jobs
logging:
  level:
    root: warn
