spring:
  application:
    name: 07-data-mongodb
  threads:
    virtual:
      enabled: true
  mongodb:
    database: bookstore
  data:
    mongodb:
      auto-index-creation: true
      representation:
        big-decimal: decimal128
