apiVersion: v1
kind: Secret
metadata:
  name: bookstore
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ include "bookstore.secretValue" (list .Values.jwtSecret "jwt-secret" .) }}
  postgres-password: {{ include "bookstore.secretValue" (list .Values.postgresPassword "postgres-password" .) }}
